
	drop proc SIEGFRIED.CREATE_TABLES_AND_FILL
	drop proc SIEGFRIED.LOAD_ESPECIALIDADES
	drop proc SIEGFRIED.LOAD_ESTADOS_CIVILES
	drop proc SIEGFRIED.LOAD_PLANES
	drop proc SIEGFRIED.LOAD_ROLES_Y_FUNCIONALIDADES
	drop proc SIEGFRIED.LOAD_USERS


	drop table SIEGFRIED.FUNCIONALIDES_ROLES
	drop table SIEGFRIED.AGENDA
	drop table SIEGFRIED.BONOS
	drop table SIEGFRIED.CANCELACION
	drop table SIEGFRIED.CONSULTAS
	drop table SIEGFRIED.ESPECIALIDADES
	drop table SIEGFRIED.FUNCIONALIDADES
	drop table SIEGFRIED.PROFESIONAL_ESPECIALIDAD
	drop table SIEGFRIED.ROLES_USUARIOS
	drop table SIEGFRIED.ROLES
	drop table SIEGFRIED.TIPOS_CANCELACION
	drop table SIEGFRIED.TIPOS_ESPECIALIDADES
	drop table SIEGFRIED.TURNOS
	drop table SIEGFRIED.AFILIADOS
	drop table SIEGFRIED.USUARIOS
	drop table SIEGFRIED.PROFESIONALES
	drop table SIEGFRIED.ESTADOS_CIVILES
	DROP TABLE SIEGFRIED.HISTORIAL_USUARIOS_PLANES
	drop table SIEGFRIED.PLANES

	drop schema SIEGFRIED
